### ISSUE TITLE
(0, i.createRoot) is not a function

### ISSUE THREAD

**Issue by tkozuch** [decaporg/gatsby-plugin-decap-cms#4]
While following https://decapcms.org/docs/start-with-a-template/ -> Gatsby Site Starter - deploy to Netlify

The process created repository, deployed the app, and sent invite. Then, after I accepted invite, and created password, I tried to access the /admin page. 

The page however appears blank and I get the following error in the console:

```
Uncaught TypeError: (0 , i.createRoot) is not a function
    at t.default [as init] (decap-cms-app.js:393:85813)
    at cms.js:21:24
    at cms.js:29:43
    at cms.js:16:37
```
    
 full output:
 
 ```
decap-cms-app 3.1.2
decap-cms-app.js:393 decap-cms-core 3.3.2
decap-cms-app.js:393 Uncaught TypeError: (0 , i.createRoot) is not a function
    at t.default [as init] (decap-cms-app.js:393:85813)
    at cms.js:21:24
    at cms.js:29:43
    at cms.js:16:37
browser-polyfill.js:1 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) Error
    at n (chrome-extension://dacdinoicboceafielngnmjjplncljhj/lib/js/browser-polyfill.js:1:8113)
n @ browser-polyfill.js:1
Pokaż jeszcze 1 ramkę
Pokaż mniej
decap-cms-app.js:14 Manually initializing identity widget
```

the website:
https://main--neon-pika-ce1973.netlify.app/admin/#/

the repository:
https://github.com/tkozuch/gatsby-starter-decap-cms

is this a known issue? any way I can fix this?

KR

**Comment by martinjagodic** [comment]
Hi @tkozuch this is not a known issue. A fix would be very appreciated :)

I am not very familiar with this template so you would have to dig in your own. If you have any other suggestions feel free to submit issues or even better - pull requests.

**Comment by woldtwerk** [comment]
Just encountered the same issue following: https://github.com/decaporg/decap-cms/blob/main/packages/decap-cms-app/README.md

The issue is that the docs say to use react@16. You have to use 18.2.0 though
